# Main server configuration. Actually you don't want to change it,
# but you able to change host or port, that will be used by serve command
server:
  host: localhost
  port: 80

# Both of web or worker depends on storage.
storage:
  # For now app require Redis and don't support any other backends to store
  # skins, but in the future we can have more backends. Poll size tune amount
  # of connections to the redis. It's not recommended to set it less then 2
  # because it will lead to panic on high load.
  redis:
    host: localhost
    port: 6379
    poolSize: 10

  # Filesystem storage used to store capes. basePath specify absolute or relative
  # path to storage and capesDirName specify which folder in this base path will
  # be used to search capes.
  filesystem:
    basePath: data
    capesDirName: capes

# StatsD can be used to collect metrics
# statsd:
#   addr: localhost:3746

# Sentry can be used to collect app errors
# sentry:
#   dsn: "https://public:private@your.sentry.io/1"
