# This file can be used to run application in the production environment.
# Copy it into the docker-compose.yml:
# > cp docker-compose.prod.yml docker-compose.yml
# And then run it:
# > docker-compose up -d
# Service will be listened at the http://localhost

version: '2'
services:
  app:
    image: elyby/chrly
    hostname: chrly0
    restart: always
    links:
      - redis
    volumes:
      - ./data/capes:/data/capes
    ports:
      - "80:80"
    environment:
      CHRLY_SECRET: replace_this_value_in_production

  # Use this configuration in case when you need a remote Mojang UUIDs provider
  # worker:
  #   image: elyby/chrly
  #   hostname: chrly0
  #   restart: always
  #   ports:
  #     - "8080:80"
  #   command: ["worker"]

  redis:
    image: redis:4.0-32bit # 32-bit version is recommended to spare some memory
    restart: always
    volumes:
      - ./data/redis:/data
