version: '2'
services:
    app:
        image: registry.ely.by/elyby/skinsystem:latest
        ports:
            - "80:80"
        links:
            - redis
            - rabbitmq
        restart: always
        environment:
            ACCOUNTS_API_ID: ""
            ACCOUNTS_API_SECRET: ""
            STATSD_ADDR: ""

    redis:
        extends:
            file: docker-compose.base.yml
            service: redis
        restart: always

    rabbitmq:
        extends:
            file: docker-compose.base.yml
            service: rabbitmq
        restart: always
