version: '2'
services:
    app:
        extends:
            file: docker-compose.base.yml
            service: app
        build: .
        volumes:
            - ./:/go/src/app
        command: ["go", "run", "minecraft-skinsystem.go"]
        links:
            - redis
            - rabbitmq

    redis:
        extends:
            file: docker-compose.base.yml
            service: redis

    rabbitmq:
        extends:
            file: docker-compose.base.yml
            service: rabbitmq
