version: '2'
services:
    app:
        image: registry.gitlab.com/elyby/skinsystem:latest
        ports:
            - "80:80"
        links:
            - redis
            - rabbitmq
        restart: always

    redis:
        extends:
            file: docker-compose.base.yml
            service: redis
        restart: always

    rabbitmq:
        extends:
            file: docker-compose.base.yml
            service: rabbitmq
        restart: always
