version: '2'
services:
    app:
        build: .
        image: registry.ely.by/elyby/skinsystem:latest
        ports:
            - "80:80"
        volumes:
            - ./:/go/src/app
        command: ["go", "run", "minecraft-skinsystem.go"]
        links:
            - redis
            - rabbitmq

    redis:
        extends:
            file: docker-compose.base.yml
            service: redis

    rabbitmq:
        extends:
            file: docker-compose.base.yml
            service: rabbitmq
