# This compose file contains necessary docker-compose config to quick start
# services required by app. Ports published to host.
#
# Usage:
# 1. Clone this file as docker-compose.yml:
#    cp docker-compose.dev.yml docker-compose.yml
#
# 2. If necessary, then you can fix configuration to your environment.
#    Then start all services:
#    docker-compose up -d
#
# 3. Pass to the project configuration links to this services:
#    amqp:
#      host: localhost
#      port: 5672
#      username: ely
#      password: ely
#      vhost: /ely
#
#    storage:
#      redis:
#        host: localhost
#        port: 6379
#        poolSize: 10
#
# 4. After job is done all services can be stopped:
#    docker-compose stop

version: '2'
services:
  redis:
    image: redis:3.2-32bit
    ports:
      - "6379:6379"
    volumes:
      - ./data/redis:/data

  rabbitmq:
    image: rabbitmq:3.6-management-alpine
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: "ely"
      RABBITMQ_DEFAULT_PASS: "ely"
      RABBITMQ_DEFAULT_VHOST: "/ely"
