version: '2'
services:
    redis:
        image: redis:3.0-alpine
        volumes:
            - ./data/redis:/data

    rabbitmq:
        image: rabbitmq:3.6
        environment:
            RABBITMQ_DEFAULT_USER: "ely-skinsystem-app"
            RABBITMQ_DEFAULT_PASS: "ely-skinsystem-app-password"
            RABBITMQ_DEFAULT_VHOST: "/ely"

    statsd:
        image: hopsoft/graphite-statsd
        volumes:
            - ./data/statsd:/opt/graphite/storage
            - ./data/graphite-config:/opt/graphite/conf
            - ./data/statsd-config/config.json:/opt/statsd/config.js
