version: '2'
services:
  web:
    image: registry.ely.by/elyby/skinsystem:latest
    restart: always
    ports:
      - "80:80"
    links:
      - redis
    volumes:
      - ./data/capes:/data/capes
      - ./config/minecraft-skinsystem:/etc/minecraft-skinsystem

  redis:
    image: redis:3.2-32bit # 32-bit version used to decrease memory usage
    restart: always
    volumes:
      - ./data/redis:/data
